version: "3.8"
services:
  back-end:
    container_name: back-end
    image: roblewisqa/prize_project/back-end:latest
    build: ./back-end
    ports:
    - target: 5000
      protocol: tcp
    environment: 
      DATABASE_URI: ${DATABASE_URI}

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  
  random_numbers:
    container_name: random_numbers
    image: roblewisqa/prize_project/random_numbers:latest
    build: ./random_numbers
    ports:
    - target: 5001
      protocol: tcp

  random_letters:
    container_name: random_letters
    image: roblewisqa/prize_project/random_letters:latest
    build: ./random_letters
    ports:
    - target: 5002
      protocol: tcp

  frontend:
    container_name: frontend
    image: roblewisqa/prize_project/frontend:latest
    build: ./frontend
    ports:
    - target: 5003
      published: 5003
      protocol: tcp