version: "3.8"
services:
  back-end:
    container_name: back-end
    image: back-end:latest
    build: ./back-end
    ports:
    - target: 5000
      protocol: tcp

  db: 
    container_name: mysql
    build: ./db
    environment:
      MYSQL_DATABASE: flask-db
      MYSQL_ROOT_PASSWORD: password
    ports:
    - target: 3306
      protocol: tcp

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  
  random_numbers:
    container_name: random_numbers
    image: random_numbers:latest
    build: ./random_numbers
    ports:
    - target: 5001
      protocol: tcp

  random_letters:
    container_name: random_letters
    image: random_letters:latest
    build: ./random_letters
    ports:
    - target: 5002
      protocol: tcp

  frontend:
    container_name: frontend
    image: frontend:latest
    build: ./frontend
    ports:
    - target: 5003
      published: 5003
      protocol: tcp