---
# tasks file for docker
- name: installing dependencies for docker  
  become: true
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3
    - pip
    state: latest
    update_cache: true

- name: get docker APT key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: get docker repo
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release|lower }} stable
    state: present

- name: install docker engine
  become: true
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true
  
- name: add user to docker group
  become: true
  user:
    name: Rob
    groups: docker
    append: yes
