---
# tasks file for worker
- name: add nodes
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ inventory_hostname }}"
    join_token: "{{ hostvars['manager-main']['swarm_data']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'manager-main:2377' ]
