---
# tasks file for manager
- name: Init a new swarm with default parameters
  become: true
  community.docker.docker_swarm:
    state: present
  register: swarm_data

- name: print swarm data
  debug:
    msg: "{{ swarm_data }}"
